#include "stdafx.h"
#include "MFCApplication1.h"
#include "MFCApplication1Dlg.h"
#include "afxdialogex.h"
#include <string>
#include <vector>
#include <string>
#include <list>
#include <string>
#include <algorithm>
#include <exception>
#include "Street.h"
#include "afxcmn.h"
#include "afxwin.h"